### ISSUE TITLE
enlightenment.eclass is getting removed from ::gentoo

### ISSUE THREAD

**Issue by juippis** [niifaq/enlightenment.overlay#6]
Hey, 

I saw you still have few packages using **enlightenment.eclass**. Just a heads-up: It's going to get removed from ::gentoo repository in ~30 days. 
https://archives.gentoo.org/gentoo-dev/message/ead472b098191f8668a105c5738995b4
https://bugs.gentoo.org/666460

You can update your ebuilds not to depend on this, or you can copy the eclass to your overlay.
https://github.com/gentoo/gentoo/blob/3e8ec0df0d136f81859982abcac18a83e40efc2f/eclass/enlightenment.eclass

Let's keep E alive in Gentoo, and have a nice day :)

**Comment by evadim** [comment]
Hi,

Thank you for the info!
I grep in repo, and see no **enlightenment.eclass** here. If you name those packages it wold be great, but very surprising: from long time ago we use our own **efl.eclass** and should be unaffected.

Anyway, looks like time to dig into overlay and look to meson things.

**Comment by juippis** [comment]
Not at my computer right now, but for example: 
https://github.com/niifaq/enlightenment.overlay/blob/master/x11-wm/enlightenment/enlightenment-0.19.4.ebuild#L17

I don't outright remember if there were more, but I think I ran something like `grep -r inherit | grep enlightenment` to print them all.
