### ISSUE TITLE
Issues regarding @enlightenment-modules set

### ISSUE THREAD

**Issue by waebbl** [niifaq/enlightenment.overlay#9]
Trying to merge the enlightenment-modules set, I got a lot of failures. 33 out of 43 packages were failing. A lot of them, it seems, because they still try to use the old svn host instead of the git host. I could fix a few of them, but most seem not available on the git host anymore. I prepare a PR for this with the ones I could fix.

Others fail to compile, I might come up with additional issues for them.

**Comment by evadim** [comment]
Better late, than never? Anyway, merged.
Thanks.

**Comment by evadim** [comment]
Better late, than never? Anyway, merged.
Thanks.
